[package]
name = "chain"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chrono = "0.4.38"
data-encoding = "2.6.0"
serde = { version = "1.0.132", features = ["derive"] }
num-bigint = "0.4.6"
ring = "0.17.8"
sha256 = "1.5.0"
